### ISSUE TITLE
Error de conexión mysql

### ISSUE THREAD

**Issue by cristianinc** [kodetop/docker-php-mysql#10]
Al realizar la instalación no pude conectar mysql con el contenedor web.
si pude acceder desde fuera del contenedor.

**Comment by gibloomis** [comment]
Me pasa lo mismo, te solucionaron?

**Comment by kodetop** [comment]
En la caso del contenedor `mysql`, tiene dos opciones para acceder:

* Para acceder desde el contenedor (servidor web), es decir desde tus archivos php, debes usar el host: `mysql`
* Para acceder desde un cliente en tu computadora, debes usar el host: `localhost`

Esto es por que php y mysql están en una misma red interna de docker y por ello para acceder internamente debes usar `mysql`
