### ISSUE TITLE
problema con el parametro php volumes

### ISSUE THREAD

**Issue by kisamat** [kodetop/docker-php-mysql#6]
Buenas tardes

Estoy intentado correr su ejemplo para un docker con php pero tengo el problema en el parametro

`volumes: 
      - ./www:`

entiendo que la segunda parte sería el lugar donde tengo mi aplicación local para mi ejemplo

`/www/docker/prueba`

entonces el parametro quedaría
`volumes:
      - ./www:/www/docker/prueba`

Al lanzar el docker e intentar ingresar al localhost siempre sale lo siguiente:

`docker-php | [Tue Jul 28 21:55:59.186327 2020] [autoindex:error] [pid 16] [client 172.18.0.1:47204] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
`

Espero me puedan ayudar

**Comment by kodetop** [comment]
Hola *kisamat*, la opción `volumes` sirve para mapear la carpeta local (donde se encuentran los archivos PHP) hacia la carpeta de publicación del servidor web en docker.

`- /carpeta-local:/carpeta-servidor-docker`

Para este repositorio, la carpeta local `www` es donde se deben colocar los archivos PHP y se reflejarán automáticamente en la carpeta interna de Docker `/var/www/html`.

En resumen: no es necesario que modifiques las configuración de Docker, sólo hace falta que coloques tus archivos PHP en la carpeta `www` de este repositorio.
