### ISSUE TITLE
"No such file or directory" al intentar conectar a la DB

### ISSUE THREAD

**Issue by jonathanhecl** [kodetop/docker-php-mysql#8]
Usando la configuración por defecto, no puedo conectarme la DB. Tira de error `No such file or directory`

```
# MySQL Options
MYSQL_VERSION=5.7
MYSQL_USER=dbuser
MYSQL_PASSWORD=dbpass
MYSQL_DATABASE=dbname
```

![imagen_2020-12-28_123827](https://user-images.githubusercontent.com/1691623/103225839-95b2fa00-4909-11eb-821f-7f2ff925c7d6.png)

**Comment by kodetop** [comment]
Hola, existen dos dominios para conectarse a base de datos.

* `mysql`: para conexión desde los archivos PHP, o conexiones desde el mismo contenedor.
* `localhost`: para conexiones externas al contenedor, por ejemplo un cliente cómo Navicat.

Entonces: en el parámetro **Servidor**, coloca `mysql` para que funcione tu conexión
