### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by jamilMX** [kodetop/docker-php-mysql#9]
Both containers are up but when I tried open localhost I got Forbidden You don't have permission to access this resource.
![Screenshot from 2021-11-25 13-43-29](https://user-images.githubusercontent.com/69217930/143494249-78b2fbec-302e-44a3-b6a6-212c2985fbb7.png)

**Comment by AGrandesR** [comment]
Hi! It's normal I have the same issue it is because you don't create a index.php and don't found the file you try to access.
Try to create a index.php file on www folder and it will work! 
Good luck!

**Comment by kodetop** [comment]
La carpeta `www` no incluye un archivo de inicio, puedes incluir un archivo `index.php` y verás el resultado sin problemas.
